_target_: src.dataset.heat1d.PINNHeatEquation1DDataset
t_domain: [0.0, 1.0]
x_domain: [0.0, 1.0]
alpha: 0.01
ic_batch_size: 100
bc_batch_size: 100
collocation_batch_size: [100, 100]
ic_sampling: grid
bc_sampling: grid
collocation_sampling: grid
resample_step: null
seed: 42
